version: '3.8'

services:
  api-gateway:
    container_name: api_gateway
    build: ./
    ports:
      - "8090:8090"
    networks:
      - global-network

# Docker Networks
networks:
  global-network:
    external: true 