// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: protos/borrower.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowerCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserID     string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BookID     string `protobuf:"bytes,3,opt,name=BookID,proto3" json:"BookID,omitempty"`
	BorrowDate string `protobuf:"bytes,4,opt,name=BorrowDate,proto3" json:"BorrowDate,omitempty"`
	ReturnDate string `protobuf:"bytes,5,opt,name=ReturnDate,proto3" json:"ReturnDate,omitempty"`
}

func (x *BorrowerCreate) Reset() {
	*x = BorrowerCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowerCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowerCreate) ProtoMessage() {}

func (x *BorrowerCreate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowerCreate.ProtoReflect.Descriptor instead.
func (*BorrowerCreate) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowerCreate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BorrowerCreate) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BorrowerCreate) GetBookID() string {
	if x != nil {
		return x.BookID
	}
	return ""
}

func (x *BorrowerCreate) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *BorrowerCreate) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

type Borrower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserID     string `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BookID     string `protobuf:"bytes,3,opt,name=BookID,proto3" json:"BookID,omitempty"`
	BorrowDate string `protobuf:"bytes,4,opt,name=BorrowDate,proto3" json:"BorrowDate,omitempty"`
	ReturnDate string `protobuf:"bytes,5,opt,name=ReturnDate,proto3" json:"ReturnDate,omitempty"`
}

func (x *Borrower) Reset() {
	*x = Borrower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrower) ProtoMessage() {}

func (x *Borrower) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrower.ProtoReflect.Descriptor instead.
func (*Borrower) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{1}
}

func (x *Borrower) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Borrower) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Borrower) GetBookID() string {
	if x != nil {
		return x.BookID
	}
	return ""
}

func (x *Borrower) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *Borrower) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

type Borrowers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Borrowers []*Borrower `protobuf:"bytes,1,rep,name=Borrowers,proto3" json:"Borrowers,omitempty"`
}

func (x *Borrowers) Reset() {
	*x = Borrowers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Borrowers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Borrowers) ProtoMessage() {}

func (x *Borrowers) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Borrowers.ProtoReflect.Descriptor instead.
func (*Borrowers) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{2}
}

func (x *Borrowers) GetBorrowers() []*Borrower {
	if x != nil {
		return x.Borrowers
	}
	return nil
}

type BorrowingHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*BorrowedBook `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *BorrowingHistory) Reset() {
	*x = BorrowingHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowingHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowingHistory) ProtoMessage() {}

func (x *BorrowingHistory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowingHistory.ProtoReflect.Descriptor instead.
func (*BorrowingHistory) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{3}
}

func (x *BorrowingHistory) GetBooks() []*BorrowedBook {
	if x != nil {
		return x.Books
	}
	return nil
}

type BorrowedBooks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Books []*BorrowedBook `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
}

func (x *BorrowedBooks) Reset() {
	*x = BorrowedBooks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowedBooks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBooks) ProtoMessage() {}

func (x *BorrowedBooks) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBooks.ProtoReflect.Descriptor instead.
func (*BorrowedBooks) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{4}
}

func (x *BorrowedBooks) GetBooks() []*BorrowedBook {
	if x != nil {
		return x.Books
	}
	return nil
}

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{5}
}

func (x *UserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type OverdueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentDate string `protobuf:"bytes,1,opt,name=current_date,json=currentDate,proto3" json:"current_date,omitempty"`
}

func (x *OverdueRequest) Reset() {
	*x = OverdueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OverdueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverdueRequest) ProtoMessage() {}

func (x *OverdueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverdueRequest.ProtoReflect.Descriptor instead.
func (*OverdueRequest) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{6}
}

func (x *OverdueRequest) GetCurrentDate() string {
	if x != nil {
		return x.CurrentDate
	}
	return ""
}

type BorrowedBook struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Book       *Book  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	BorrowDate string `protobuf:"bytes,2,opt,name=borrow_date,json=borrowDate,proto3" json:"borrow_date,omitempty"`
	ReturnDate string `protobuf:"bytes,3,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
}

func (x *BorrowedBook) Reset() {
	*x = BorrowedBook{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_borrower_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowedBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBook) ProtoMessage() {}

func (x *BorrowedBook) ProtoReflect() protoreflect.Message {
	mi := &file_protos_borrower_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBook.ProtoReflect.Descriptor instead.
func (*BorrowedBook) Descriptor() ([]byte, []int) {
	return file_protos_borrower_proto_rawDescGZIP(), []int{7}
}

func (x *BorrowedBook) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *BorrowedBook) GetBorrowDate() string {
	if x != nil {
		return x.BorrowDate
	}
	return ""
}

func (x *BorrowedBook) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

var File_protos_borrower_proto protoreflect.FileDescriptor

var file_protos_borrower_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a,
	0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x6f, 0x6f,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01, 0x0a, 0x0e, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x42,
	0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x42, 0x6f, 0x72,
	0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x3b, 0x0a, 0x09, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x09, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x09, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x10, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62,
	0x6f, 0x6f, 0x6b, 0x73, 0x22, 0x3b, 0x0a, 0x0d, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x22, 0x20, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0e, 0x4f, 0x76, 0x65, 0x72, 0x64, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x65, 0x22, 0x72, 0x0a, 0x0c, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x6f, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x04, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f,
	0x72, 0x72, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x32, 0xd3, 0x03, 0x0a,
	0x0f, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3c, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x00, 0x12, 0x2f,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65,
	0x72, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f,
	0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x79, 0x49, 0x64, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x12, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x73, 0x22, 0x00, 0x12,
	0x36, 0x0a, 0x0d, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x72, 0x42, 0x6f, 0x6f, 0x6b, 0x73,
	0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77,
	0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x40, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x76,
	0x65, 0x72, 0x64, 0x75, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4f, 0x76, 0x65, 0x72, 0x64, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72,
	0x6f, 0x77, 0x65, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x48, 0x69, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_borrower_proto_rawDescOnce sync.Once
	file_protos_borrower_proto_rawDescData = file_protos_borrower_proto_rawDesc
)

func file_protos_borrower_proto_rawDescGZIP() []byte {
	file_protos_borrower_proto_rawDescOnce.Do(func() {
		file_protos_borrower_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_borrower_proto_rawDescData)
	})
	return file_protos_borrower_proto_rawDescData
}

var file_protos_borrower_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_borrower_proto_goTypes = []interface{}{
	(*BorrowerCreate)(nil),   // 0: protos.BorrowerCreate
	(*Borrower)(nil),         // 1: protos.Borrower
	(*Borrowers)(nil),        // 2: protos.Borrowers
	(*BorrowingHistory)(nil), // 3: protos.BorrowingHistory
	(*BorrowedBooks)(nil),    // 4: protos.BorrowedBooks
	(*UserId)(nil),           // 5: protos.UserId
	(*OverdueRequest)(nil),   // 6: protos.OverdueRequest
	(*BorrowedBook)(nil),     // 7: protos.BorrowedBook
	(*Book)(nil),             // 8: protos.Book
	(*ById)(nil),             // 9: protos.ById
	(*Void)(nil),             // 10: protos.Void
}
var file_protos_borrower_proto_depIdxs = []int32{
	1,  // 0: protos.Borrowers.Borrowers:type_name -> protos.Borrower
	7,  // 1: protos.BorrowingHistory.books:type_name -> protos.BorrowedBook
	7,  // 2: protos.BorrowedBooks.books:type_name -> protos.BorrowedBook
	8,  // 3: protos.BorrowedBook.book:type_name -> protos.Book
	0,  // 4: protos.BorrowerService.CreateBorrower:input_type -> protos.BorrowerCreate
	9,  // 5: protos.BorrowerService.GetBorrower:input_type -> protos.ById
	0,  // 6: protos.BorrowerService.UpdateBorrower:input_type -> protos.BorrowerCreate
	9,  // 7: protos.BorrowerService.DeleteBorrower:input_type -> protos.ById
	10, // 8: protos.BorrowerService.GetAllBorrowers:input_type -> protos.Void
	5,  // 9: protos.BorrowerService.BorrowerBooks:input_type -> protos.UserId
	6,  // 10: protos.BorrowerService.GetOverdueBooks:input_type -> protos.OverdueRequest
	5,  // 11: protos.BorrowerService.HistoryUser:input_type -> protos.UserId
	1,  // 12: protos.BorrowerService.CreateBorrower:output_type -> protos.Borrower
	1,  // 13: protos.BorrowerService.GetBorrower:output_type -> protos.Borrower
	10, // 14: protos.BorrowerService.UpdateBorrower:output_type -> protos.Void
	10, // 15: protos.BorrowerService.DeleteBorrower:output_type -> protos.Void
	2,  // 16: protos.BorrowerService.GetAllBorrowers:output_type -> protos.Borrowers
	4,  // 17: protos.BorrowerService.BorrowerBooks:output_type -> protos.BorrowedBooks
	4,  // 18: protos.BorrowerService.GetOverdueBooks:output_type -> protos.BorrowedBooks
	3,  // 19: protos.BorrowerService.HistoryUser:output_type -> protos.BorrowingHistory
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_protos_borrower_proto_init() }
func file_protos_borrower_proto_init() {
	if File_protos_borrower_proto != nil {
		return
	}
	file_protos_common_proto_init()
	file_protos_book_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_borrower_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowerCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Borrowers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowingHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowedBooks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OverdueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_borrower_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowedBook); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_borrower_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_borrower_proto_goTypes,
		DependencyIndexes: file_protos_borrower_proto_depIdxs,
		MessageInfos:      file_protos_borrower_proto_msgTypes,
	}.Build()
	File_protos_borrower_proto = out.File
	file_protos_borrower_proto_rawDesc = nil
	file_protos_borrower_proto_goTypes = nil
	file_protos_borrower_proto_depIdxs = nil
}
