// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protos/genre.proto

package genproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GenreServiceClient is the client API for GenreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenreServiceClient interface {
	CreateGenre(ctx context.Context, in *GenreCreate, opts ...grpc.CallOption) (*Genre, error)
	GetGenre(ctx context.Context, in *ByName, opts ...grpc.CallOption) (*GenreCreate, error)
	UpdateGenre(ctx context.Context, in *GenreCreate, opts ...grpc.CallOption) (*Void, error)
	DeleteGenre(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error)
	GetAllGenres(ctx context.Context, in *NameFilter, opts ...grpc.CallOption) (*Genres, error)
	GetBooksByGenre(ctx context.Context, in *GenreId, opts ...grpc.CallOption) (*GenreBooks, error)
}

type genreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenreServiceClient(cc grpc.ClientConnInterface) GenreServiceClient {
	return &genreServiceClient{cc}
}

func (c *genreServiceClient) CreateGenre(ctx context.Context, in *GenreCreate, opts ...grpc.CallOption) (*Genre, error) {
	out := new(Genre)
	err := c.cc.Invoke(ctx, "/protos.GenreService/CreateGenre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) GetGenre(ctx context.Context, in *ByName, opts ...grpc.CallOption) (*GenreCreate, error) {
	out := new(GenreCreate)
	err := c.cc.Invoke(ctx, "/protos.GenreService/GetGenre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) UpdateGenre(ctx context.Context, in *GenreCreate, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.GenreService/UpdateGenre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) DeleteGenre(ctx context.Context, in *ById, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.GenreService/DeleteGenre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) GetAllGenres(ctx context.Context, in *NameFilter, opts ...grpc.CallOption) (*Genres, error) {
	out := new(Genres)
	err := c.cc.Invoke(ctx, "/protos.GenreService/GetAllGenres", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *genreServiceClient) GetBooksByGenre(ctx context.Context, in *GenreId, opts ...grpc.CallOption) (*GenreBooks, error) {
	out := new(GenreBooks)
	err := c.cc.Invoke(ctx, "/protos.GenreService/GetBooksByGenre", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenreServiceServer is the server API for GenreService service.
// All implementations must embed UnimplementedGenreServiceServer
// for forward compatibility
type GenreServiceServer interface {
	CreateGenre(context.Context, *GenreCreate) (*Genre, error)
	GetGenre(context.Context, *ByName) (*GenreCreate, error)
	UpdateGenre(context.Context, *GenreCreate) (*Void, error)
	DeleteGenre(context.Context, *ById) (*Void, error)
	GetAllGenres(context.Context, *NameFilter) (*Genres, error)
	GetBooksByGenre(context.Context, *GenreId) (*GenreBooks, error)
	mustEmbedUnimplementedGenreServiceServer()
}

// UnimplementedGenreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGenreServiceServer struct {
}

func (UnimplementedGenreServiceServer) CreateGenre(context.Context, *GenreCreate) (*Genre, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGenre not implemented")
}
func (UnimplementedGenreServiceServer) GetGenre(context.Context, *ByName) (*GenreCreate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGenre not implemented")
}
func (UnimplementedGenreServiceServer) UpdateGenre(context.Context, *GenreCreate) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGenre not implemented")
}
func (UnimplementedGenreServiceServer) DeleteGenre(context.Context, *ById) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGenre not implemented")
}
func (UnimplementedGenreServiceServer) GetAllGenres(context.Context, *NameFilter) (*Genres, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllGenres not implemented")
}
func (UnimplementedGenreServiceServer) GetBooksByGenre(context.Context, *GenreId) (*GenreBooks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooksByGenre not implemented")
}
func (UnimplementedGenreServiceServer) mustEmbedUnimplementedGenreServiceServer() {}

// UnsafeGenreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenreServiceServer will
// result in compilation errors.
type UnsafeGenreServiceServer interface {
	mustEmbedUnimplementedGenreServiceServer()
}

func RegisterGenreServiceServer(s grpc.ServiceRegistrar, srv GenreServiceServer) {
	s.RegisterService(&GenreService_ServiceDesc, srv)
}

func _GenreService_CreateGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).CreateGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/CreateGenre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).CreateGenre(ctx, req.(*GenreCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_GetGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ByName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).GetGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/GetGenre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).GetGenre(ctx, req.(*ByName))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_UpdateGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).UpdateGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/UpdateGenre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).UpdateGenre(ctx, req.(*GenreCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_DeleteGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).DeleteGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/DeleteGenre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).DeleteGenre(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_GetAllGenres_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).GetAllGenres(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/GetAllGenres",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).GetAllGenres(ctx, req.(*NameFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _GenreService_GetBooksByGenre_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenreId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenreServiceServer).GetBooksByGenre(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.GenreService/GetBooksByGenre",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenreServiceServer).GetBooksByGenre(ctx, req.(*GenreId))
	}
	return interceptor(ctx, in, info, handler)
}

// GenreService_ServiceDesc is the grpc.ServiceDesc for GenreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.GenreService",
	HandlerType: (*GenreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGenre",
			Handler:    _GenreService_CreateGenre_Handler,
		},
		{
			MethodName: "GetGenre",
			Handler:    _GenreService_GetGenre_Handler,
		},
		{
			MethodName: "UpdateGenre",
			Handler:    _GenreService_UpdateGenre_Handler,
		},
		{
			MethodName: "DeleteGenre",
			Handler:    _GenreService_DeleteGenre_Handler,
		},
		{
			MethodName: "GetAllGenres",
			Handler:    _GenreService_GetAllGenres_Handler,
		},
		{
			MethodName: "GetBooksByGenre",
			Handler:    _GenreService_GetBooksByGenre_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/genre.proto",
}
